var WebSocket = require('ws');
var WebSocketServer = WebSocket.Server;
var port = 3001;
var ws = new WebSocketServer({
  port: port
});
var messages = [];

console.log('Websocket server started');

ws.on('connection', function (socket) {
  console.log('Client connection established');
  // establish connection events for WebSocket server

  messages.forEach(function (msg){
    socket.send(msg); //allow new users to see older messages
  });

  socket.on('message', function (data) {
    console.log('message received: ' + data);
    messages.push(data); //to keep track of all messages
    ws.clients.forEach(function (clientSocket) { //clients is an array
      clientSocket.send(data);
    //sends new messages to all users as each new message comes in
    });
  // set up echo server, which is registering any callback for any message events
  // generated by the client connection. Server will repeat messages received from
  // client. To initiate, in terminal enter "wscat -c ws://localhost:3001"
  });
});
